services:
  - type: web
    name: medicaid-dashboard
    runtime: docker
    plan: starter
    region: virginia
    repo: https://github.com/benashkar/medicaid-provider-spending
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: DB_NAME
        value: medicaid_spending
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
